[package]
name = "bananabar"
version = "0.1.0"
edition = "2021"

[dependencies]
unicode-segmentation = "1.10.1"
x11 = { version = "2.21.0", features = ["xft"] }
xcb = { version = "1.2.1", features = ["xlib_xcb", "randr"] }
